export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_ADD_FIELD_VALUE = 'SET_ADD_FIELD_VALUE';
export const ADD_TODO_ITEM = 'ADD_TODO_ITEM';
export const TOGGLE_IMPORTANT_ITEM = 'TOGGLE_IMPORTANT_ITEM';
export const SET_FILTER_VALUE = 'SET_FILTER_VALUE';